/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "account_record_test.ts" instead.
 */

#include <check.h>

#line 1 "account_record_test.ts"
#include "account.h"
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <check.h>

account_t *mock_account;

START_TEST(login_success)
{
#line 12
    // Test that a successful login updates the correct fields.
    mock_account = account_create("user1", "abc123", "a@example.com", "2000-01-01");
    ip4_addr_t ip = 0x7f000001; // 127.0.0.1
    account_record_login_success(mock_account, ip);
    ck_assert_int_eq(mock_account->login_count, 1);
    ck_assert_int_eq(mock_account->login_fail_count, 0);
    ck_assert_uint_ne(mock_account->last_login_time, 0);
    ck_assert_uint_eq(mock_account->last_ip, ip);
    account_free(mock_account);

}
END_TEST

START_TEST(login_failure)
{
#line 23
    // Test that a failed login updates the fail count and resets login count.
    mock_account = account_create("user2", "def456", "b@example.com", "2000-01-01");
    account_record_login_failure(mock_account);
    ck_assert_int_eq(mock_account->login_fail_count, 1);
    ck_assert_int_eq(mock_account->login_count, 0);
    account_free(mock_account);

}
END_TEST

START_TEST(login_success_null)
{
#line 31
    // Test that login success function handles NULL account without crashing.
    account_record_login_success(NULL, 0x7f000001);

}
END_TEST

START_TEST(login_failure_null)
{
#line 35
    // Test that login failure function handles NULL account without crashing.
    account_record_login_failure(NULL);

}
END_TEST

START_TEST(print_summary)
{
#line 39
    // Test that summary output works with a valid account and file descriptor.
    mock_account = account_create("user3", "ghi789", "c@example.com", "2000-01-01");
    mock_account->login_count = 5;
    mock_account->login_fail_count = 2;
    int fd = open("test_output.txt", O_WRONLY | O_CREAT | O_TRUNC, 0600);
    ck_assert_int_ne(fd, -1);
    bool result = account_print_summary(mock_account, fd);
    ck_assert(result == true);
    close(fd);
    account_free(mock_account);

}
END_TEST

START_TEST(print_summary_invalid_fd)
{
#line 51
    // Test that account_print_summary returns false for invalid file descriptor.
    mock_account = account_create("user4", "xyz", "x@example.com", "1999-12-31");
    bool result = account_print_summary(mock_account, -1);
    ck_assert(result == false);
    account_free(mock_account);

}
END_TEST

START_TEST(print_summary_null_account)
{
#line 58
    // Test that account_print_summary handles NULL input safely.
    bool result = account_print_summary(NULL, STDOUT_FILENO);
    ck_assert(result == false);

}
END_TEST

START_TEST(print_summary_invalid_ip)
{
#line 63
    // Test that invalid IP still allows summary to be written, with log warning.
    mock_account = account_create("user5", "p", "a@example.com", "2000-01-01");
    mock_account->last_ip = 0xffffffff + 1; // Invalid IPv4 (overflow)
    int fd = open("test_output.txt", O_WRONLY | O_CREAT | O_TRUNC, 0600);
    ck_assert_int_ne(fd, -1);
    bool result = account_print_summary(mock_account, fd);
    ck_assert(result == true); // Should still write successfully
    close(fd);
    account_free(mock_account);

}
END_TEST

START_TEST(print_summary_null_fields)
{
#line 74
    // Test that fallback strings are used when account fields are NULL or empty.
    mock_account = malloc(sizeof(account_t));
    memset(mock_account, 0, sizeof(account_t)); // All fields null/zeroed
    int fd = open("test_output.txt", O_WRONLY | O_CREAT | O_TRUNC, 0600);
    ck_assert_int_ne(fd, -1);
    bool result = account_print_summary(mock_account, fd);
    ck_assert(result == true); // Should print using "(unknown)" and "(none)"
    close(fd);
    free(mock_account);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, login_success);
    tcase_add_test(tc1_1, login_failure);
    tcase_add_test(tc1_1, login_success_null);
    tcase_add_test(tc1_1, login_failure_null);
    tcase_add_test(tc1_1, print_summary);
    tcase_add_test(tc1_1, print_summary_invalid_fd);
    tcase_add_test(tc1_1, print_summary_null_account);
    tcase_add_test(tc1_1, print_summary_invalid_ip);
    tcase_add_test(tc1_1, print_summary_null_fields);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
