/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "ban_expire.ts" instead.
 */

#include <check.h>

#line 1 "ban_expire.ts"
#define CITS3007_PERMISSIVE

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <stdbool.h>
#include <time.h>

#include "account.h"

#define ARR_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]))



START_TEST(test_account_is_banned_cases)
{
#line 20
//tests to see if an account is banned
  account_t acc = {0};

  acc.unban_time = 0;
  ck_assert_int_eq(account_is_banned(&acc), 0);

  acc.unban_time = time(NULL) + 3600;
  ck_assert_int_eq(account_is_banned(&acc), 1);

  acc.unban_time = time(NULL) - 3600;
  ck_assert_int_eq(account_is_banned(&acc), 0);


}
END_TEST

START_TEST(test_account_is_expired_cases)
{
#line 36
//tests to see if an account is expired
  account_t acc = {0};

  acc.expiration_time = 0;
  ck_assert_int_eq(account_is_expired(&acc), 0);

  acc.expiration_time = time(NULL) + 3600;
  ck_assert_int_eq(account_is_expired(&acc), 0);

  acc.expiration_time = time(NULL) - 3600;
  ck_assert_int_eq(account_is_expired(&acc), 1);


}
END_TEST

START_TEST(test_account_set_unban_time_cases)
{
#line 52
//tests whether the function behind setting bans and unbans actually works
  account_t acc = {0};

  time_t now = time(NULL);
  account_set_unban_time(&acc, 3600);
  ck_assert_int_le(abs((int)(acc.unban_time - now - 3600)), 1);

  now = time(NULL);
  account_set_unban_time(&acc, 0);
  ck_assert_int_le(abs((int)(acc.unban_time - now)), 1);

  now = time(NULL);
  account_set_unban_time(&acc, 86400);
  ck_assert_int_le(abs((int)(acc.unban_time - now - 86400)), 1);


}
END_TEST

START_TEST(test_account_set_expiration_time_cases)
{
#line 71
//tests whether function behind setting expiration time works
  account_t acc = {0};

  time_t now = time(NULL);
  account_set_expiration_time(&acc, 3600);
  ck_assert_int_le(abs((int)(acc.expiration_time - now - 3600)), 1);

  now = time(NULL);
  account_set_expiration_time(&acc, 0);
  ck_assert_int_le(abs((int)(acc.expiration_time - now)), 1);

  now = time(NULL);
  account_set_expiration_time(&acc, 2592000);
  ck_assert_int_le(abs((int)(acc.expiration_time - now - 2592000)), 1);

// vim: syntax=c :

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("account_suite");
    TCase *tc1_1 = tcase_create("account_is_banned_test_case");
    TCase *tc1_2 = tcase_create("account_is_expired_test_case");
    TCase *tc1_3 = tcase_create("account_set_unban_time_test_case");
    TCase *tc1_4 = tcase_create("account_set_expiration_time_test_case");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_account_is_banned_cases);
    suite_add_tcase(s1, tc1_2);
    tcase_add_test(tc1_2, test_account_is_expired_cases);
    suite_add_tcase(s1, tc1_3);
    tcase_add_test(tc1_3, test_account_set_unban_time_cases);
    suite_add_tcase(s1, tc1_4);
    tcase_add_test(tc1_4, test_account_set_expiration_time_cases);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
