// DO NOT SUBMIT THIS FILE
//
// When submitting your project, this file will be overwritten
// by the automated build and test system.
//
// DO NOT EDIT THIS FILE
//
// Since any changes you make will be lost when you submit your project.

#ifndef DB_H
#define DB_H

#include "account.h"

/**
 * @file db.h
 * @brief API for the database system.
 *
 */

/**
 * Looks up an account by user ID.
 *
 * Parameters:
 *
 * - username - user ID to look up
 * - result   - pointer to an account_t to be filled in on success
 *
 * Returns:
 *   true if the account was found and populated, false otherwise.
 */
bool account_lookup_by_userid(const char *userid, account_t *result);

#endif // DB_H

