// DO NOT SUBMIT THIS FILE
//
// When submitting your project, this file will be overwritten
// by the automated build and test system.
//
// DO NOT EDIT THIS FILE
//
// Since any changes you make will be lost when you submit your project.

#ifndef LOGGING_H
#define LOGGING_H

/**
 * @file logging.h
 * @brief API for the logging system.
 *
 * Defines log levels and declares the log_message function.
 */

#include <stdio.h>
#include <stdarg.h>

typedef enum {
  LOG_DEBUG,
  LOG_INFO,
  LOG_WARN,
  LOG_ERROR
} log_level_t;

/**
 * Log a message with the given log level.
 *
 * Calling the function with an invalid log level, invalid format string,
 * or invalid arguments results in undefined behavior.
 * 
 * Parameters:
 * - level The severity level (e.g., LOG_INFO)
 * - fmt A printf-style format string
 * - ... Format arguments
 */
void log_message(log_level_t level, const char *fmt, ...);


#endif // LOGGING_H
